### ISSUE TITLE
custom port ignored on processing URL for connecting with datasource

### ISSUE THREAD

**Issue by soletan** [vidigami/backbone-orm#54]
On trying to connect with MySQL running in a docker container, thus using non-default port number, I am observing knex trying to connect with port 3306 on proper IP address. 

So I tried to find root cause for this and found **backbone-orm**'s DatabaseURL to rely on NodeJS parsing URL resulting in `host` providing hostname incl. port number while `hostname` isn't including port number. **backbone-sql** is then using `hostname` to provide connection info for knex which is thus not including port number.

At first glance this issue seems to be more related to **backbone-sql**, however the code in `DatabaseURL` of **backbone-orm** looks rather strange. This is related to processing URL providing multiple hosts differently when compared with behaviour of NodeJS's URL parsing library as of 4.3.x.:

``` coffeescript
@hosts = []
for database in databases
  host = database.split(':')
  @hosts.push if host.length is 1 then {host: host[0], hostname: host[0]} else {host: host[0], hostname: "#{host[0]}:#{host[1]}", port: host[1]}
```

On providing multiple server addresses separated by comma this code is used and thus the resulting property per host including custom port number is `hostname` (different from NodeJS URL parsing, but would be matching expectation of backbone-sql) while on providing single host name only the result of NodeJS's URL parsing is taken as-is, so `host` is including port number rather than `hostname`. And basically I agree with NodeJS behaviour for the _name_ of host doesn't include port numbers.

**Comment by kmalakoff** [comment]
Thank you for investigating and tracking this down. Totally agree that BackboneORM should be consistent with Node.js!

Would you be willing to make DatabaseURL do what you think is right and ensure the tests for at least one SQL variant pass? (eg. edit BackboneORM and test with BackboneSQL adding at least one test for the case you found was broken)

**Comment by soletan** [comment]
Basically I'd come up with a proposal for fixing implementation, but actually I'm lacking any familiarity with Coffeescript for I feel pretty safe in using Javascript for years now. Thus, for me setting up things just to properly work with coffeescript, for building code and testing it might take a magnitude of time required for fixing and testing eventually. So, if you don't get it I will get it, though I can't promise solution any soon.

**Comment by kmalakoff** [comment]
Understood. I'm personally using ES6 / ESNext these days, but I didn't find CoffeeScript very hard to learn...use indentation, similar to some ES6 / ESNext features, drop brackets, etc.

I'm happy if you submit in working JavaScript. The CoffeeScript is compiled via webpack so you can add JavaScript pretty easily if you prefer taking on webpack to CoffeeScript.

**Comment by soletan** [comment]
It's definitely not about learning Coffeescript but becoming familiar with it (sufficiently familiar to promote patches into a community project) and getting the required eco system to run. E.g. my projects rely on grunt, backbone-orm seems to work with gulp. Trying simple installation of it ended in permission issues with Windows. Blocked. webpack? Never heard of it. So, this is really about creating a working setup, next finding time to implement and test any revision. I'm working about 60h/week on different projects in Javascript and this one (which is about to rely on backbone-orm currently) is yet another one keeping quite some clues to be solved in addition to this one. I run into several delays in contracts with my customers and that's why I don't want to distract myself with this problem. I'm pretty interested in it, as I am interested in CoffeeScript ... but time is crucial. ;)

**Comment by kmalakoff** [comment]
If you are more experienced in grunt and Windows, the pipeline might be a challenge to get working for you since we have only tested with gulp / webpack, and Linux / Mac. If you do not have the time to learn webpack (which is a pretty standard packaging solution these days) and you are busy, maybe this patch is too much for you to take on.

I am trying to encourage people to contribute to fix problems rather than myself undertaking more work since like you, I'm also already stretched thin. 

If you do not have time to contribute to make BackboneORM fit your needs, let me suggest you try another framework like: Loopback, Sails.js, ActionHero.js, or pick something from [the Awesome Node.js curated list](https://github.com/sindresorhus/awesome-nodejs) that may work better out of the box for you.

**Comment by soletan** [comment]
Thanks for the very uncommon advise and your inspirations! I'm obviously pretty off topic ;) ... indeed waterline of sails looks great.

**Comment by kmalakoff** [comment]
My pleasure! I know they all have a larger support community which probably means their tooling works on Windows...it sounds like what you need!
